//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAuthentication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Motorcycle", Namespace="http://schemas.datacontract.org/2004/07/Data.Entities")]
    [System.SerializableAttribute()]
    public partial class Motorcycle : MVCAuthentication.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAuthentication.ServiceReference1.Brand BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ManifactureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAuthentication.ServiceReference1.Sale[] SalesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddedBy {
            get {
                return this.AddedByField;
            }
            set {
                if ((object.ReferenceEquals(this.AddedByField, value) != true)) {
                    this.AddedByField = value;
                    this.RaisePropertyChanged("AddedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAuthentication.ServiceReference1.Brand Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ManifactureDate {
            get {
                return this.ManifactureDateField;
            }
            set {
                if ((this.ManifactureDateField.Equals(value) != true)) {
                    this.ManifactureDateField = value;
                    this.RaisePropertyChanged("ManifactureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAuthentication.ServiceReference1.Sale[] Sales {
            get {
                return this.SalesField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesField, value) != true)) {
                    this.SalesField = value;
                    this.RaisePropertyChanged("Sales");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Data.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MVCAuthentication.ServiceReference1.Brand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MVCAuthentication.ServiceReference1.Sale))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MVCAuthentication.ServiceReference1.Motorcycle))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Brand", Namespace="http://schemas.datacontract.org/2004/07/Data.Entities")]
    [System.SerializableAttribute()]
    public partial class Brand : MVCAuthentication.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddedFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AddedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryOfOriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short FoundedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LowestModelPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAuthentication.ServiceReference1.Motorcycle[] MotorcyclesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddedFrom {
            get {
                return this.AddedFromField;
            }
            set {
                if ((object.ReferenceEquals(this.AddedFromField, value) != true)) {
                    this.AddedFromField = value;
                    this.RaisePropertyChanged("AddedFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddedOn {
            get {
                return this.AddedOnField;
            }
            set {
                if ((this.AddedOnField.Equals(value) != true)) {
                    this.AddedOnField = value;
                    this.RaisePropertyChanged("AddedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryOfOrigin {
            get {
                return this.CountryOfOriginField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryOfOriginField, value) != true)) {
                    this.CountryOfOriginField = value;
                    this.RaisePropertyChanged("CountryOfOrigin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short FoundedIn {
            get {
                return this.FoundedInField;
            }
            set {
                if ((this.FoundedInField.Equals(value) != true)) {
                    this.FoundedInField = value;
                    this.RaisePropertyChanged("FoundedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LowestModelPrice {
            get {
                return this.LowestModelPriceField;
            }
            set {
                if ((this.LowestModelPriceField.Equals(value) != true)) {
                    this.LowestModelPriceField = value;
                    this.RaisePropertyChanged("LowestModelPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAuthentication.ServiceReference1.Motorcycle[] Motorcycles {
            get {
                return this.MotorcyclesField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorcyclesField, value) != true)) {
                    this.MotorcyclesField = value;
                    this.RaisePropertyChanged("Motorcycles");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sale", Namespace="http://schemas.datacontract.org/2004/07/Data.Entities")]
    [System.SerializableAttribute()]
    public partial class Sale : MVCAuthentication.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAuthentication.ServiceReference1.Motorcycle MotorcycleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MotorcycleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SaleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellerNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientFirstName {
            get {
                return this.ClientFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientFirstNameField, value) != true)) {
                    this.ClientFirstNameField = value;
                    this.RaisePropertyChanged("ClientFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientLastName {
            get {
                return this.ClientLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientLastNameField, value) != true)) {
                    this.ClientLastNameField = value;
                    this.RaisePropertyChanged("ClientLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAuthentication.ServiceReference1.Motorcycle Motorcycle {
            get {
                return this.MotorcycleField;
            }
            set {
                if ((object.ReferenceEquals(this.MotorcycleField, value) != true)) {
                    this.MotorcycleField = value;
                    this.RaisePropertyChanged("Motorcycle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MotorcycleID {
            get {
                return this.MotorcycleIDField;
            }
            set {
                if ((this.MotorcycleIDField.Equals(value) != true)) {
                    this.MotorcycleIDField = value;
                    this.RaisePropertyChanged("MotorcycleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((this.SaleDateField.Equals(value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalePrice {
            get {
                return this.SalePriceField;
            }
            set {
                if ((this.SalePriceField.Equals(value) != true)) {
                    this.SalePriceField = value;
                    this.RaisePropertyChanged("SalePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellerName {
            get {
                return this.SellerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerNameField, value) != true)) {
                    this.SellerNameField = value;
                    this.RaisePropertyChanged("SellerName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCurrentId", ReplyAction="http://tempuri.org/IService1/SetCurrentIdResponse")]
        void SetCurrentId(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCurrentId", ReplyAction="http://tempuri.org/IService1/SetCurrentIdResponse")]
        System.Threading.Tasks.Task SetCurrentIdAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentId", ReplyAction="http://tempuri.org/IService1/GetCurrentIdResponse")]
        int GetCurrentId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentId", ReplyAction="http://tempuri.org/IService1/GetCurrentIdResponse")]
        System.Threading.Tasks.Task<int> GetCurrentIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MVCAuthentication.ServiceReference1.CompositeType GetDataUsingDataContract(MVCAuthentication.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MVCAuthentication.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(MVCAuthentication.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBrands", ReplyAction="http://tempuri.org/IService1/GetBrandsResponse")]
        ApplicationService.DTOs.BrandDTO[] GetBrands(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBrands", ReplyAction="http://tempuri.org/IService1/GetBrandsResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BrandDTO[]> GetBrandsAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBrand", ReplyAction="http://tempuri.org/IService1/PostBrandResponse")]
        string PostBrand(ApplicationService.DTOs.BrandDTO brandDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBrand", ReplyAction="http://tempuri.org/IService1/PostBrandResponse")]
        System.Threading.Tasks.Task<string> PostBrandAsync(ApplicationService.DTOs.BrandDTO brandDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutBrand", ReplyAction="http://tempuri.org/IService1/PutBrandResponse")]
        string PutBrand(ApplicationService.DTOs.BrandDTO brandDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutBrand", ReplyAction="http://tempuri.org/IService1/PutBrandResponse")]
        System.Threading.Tasks.Task<string> PutBrandAsync(ApplicationService.DTOs.BrandDTO brandDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBrandByID", ReplyAction="http://tempuri.org/IService1/GetBrandByIDResponse")]
        ApplicationService.DTOs.BrandDTO GetBrandByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBrandByID", ReplyAction="http://tempuri.org/IService1/GetBrandByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BrandDTO> GetBrandByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBrand", ReplyAction="http://tempuri.org/IService1/DeleteBrandResponse")]
        string DeleteBrand(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBrand", ReplyAction="http://tempuri.org/IService1/DeleteBrandResponse")]
        System.Threading.Tasks.Task<string> DeleteBrandAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMotorcycles", ReplyAction="http://tempuri.org/IService1/GetMotorcyclesResponse")]
        ApplicationService.DTOs.MotorcycleDTO[] GetMotorcycles(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMotorcycles", ReplyAction="http://tempuri.org/IService1/GetMotorcyclesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.MotorcycleDTO[]> GetMotorcyclesAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMotorcycleByID", ReplyAction="http://tempuri.org/IService1/GetMotorcycleByIDResponse")]
        ApplicationService.DTOs.MotorcycleDTO GetMotorcycleByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMotorcycleByID", ReplyAction="http://tempuri.org/IService1/GetMotorcycleByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.MotorcycleDTO> GetMotorcycleByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostMotorcycle", ReplyAction="http://tempuri.org/IService1/PostMotorcycleResponse")]
        string PostMotorcycle(ApplicationService.DTOs.MotorcycleDTO motorcycleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostMotorcycle", ReplyAction="http://tempuri.org/IService1/PostMotorcycleResponse")]
        System.Threading.Tasks.Task<string> PostMotorcycleAsync(ApplicationService.DTOs.MotorcycleDTO motorcycleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutMotorcycle", ReplyAction="http://tempuri.org/IService1/PutMotorcycleResponse")]
        string PutMotorcycle(ApplicationService.DTOs.MotorcycleDTO motorcycleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutMotorcycle", ReplyAction="http://tempuri.org/IService1/PutMotorcycleResponse")]
        System.Threading.Tasks.Task<string> PutMotorcycleAsync(ApplicationService.DTOs.MotorcycleDTO motorcycleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMotorcycle", ReplyAction="http://tempuri.org/IService1/DeleteMotorcycleResponse")]
        string DeleteMotorcycle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMotorcycle", ReplyAction="http://tempuri.org/IService1/DeleteMotorcycleResponse")]
        System.Threading.Tasks.Task<string> DeleteMotorcycleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSales", ReplyAction="http://tempuri.org/IService1/GetSalesResponse")]
        ApplicationService.DTOs.SaleDTO[] GetSales(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSales", ReplyAction="http://tempuri.org/IService1/GetSalesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.SaleDTO[]> GetSalesAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSaleByID", ReplyAction="http://tempuri.org/IService1/GetSaleByIDResponse")]
        ApplicationService.DTOs.SaleDTO GetSaleByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSaleByID", ReplyAction="http://tempuri.org/IService1/GetSaleByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.SaleDTO> GetSaleByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostSale", ReplyAction="http://tempuri.org/IService1/PostSaleResponse")]
        string PostSale(ApplicationService.DTOs.SaleDTO saleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostSale", ReplyAction="http://tempuri.org/IService1/PostSaleResponse")]
        System.Threading.Tasks.Task<string> PostSaleAsync(ApplicationService.DTOs.SaleDTO saleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutSale", ReplyAction="http://tempuri.org/IService1/PutSaleResponse")]
        string PutSale(ApplicationService.DTOs.SaleDTO saleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutSale", ReplyAction="http://tempuri.org/IService1/PutSaleResponse")]
        System.Threading.Tasks.Task<string> PutSaleAsync(ApplicationService.DTOs.SaleDTO saleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSale", ReplyAction="http://tempuri.org/IService1/DeleteSaleResponse")]
        string DeleteSale(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSale", ReplyAction="http://tempuri.org/IService1/DeleteSaleResponse")]
        System.Threading.Tasks.Task<string> DeleteSaleAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MVCAuthentication.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MVCAuthentication.ServiceReference1.IService1>, MVCAuthentication.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public void SetCurrentId(int value) {
            base.Channel.SetCurrentId(value);
        }
        
        public System.Threading.Tasks.Task SetCurrentIdAsync(int value) {
            return base.Channel.SetCurrentIdAsync(value);
        }
        
        public int GetCurrentId() {
            return base.Channel.GetCurrentId();
        }
        
        public System.Threading.Tasks.Task<int> GetCurrentIdAsync() {
            return base.Channel.GetCurrentIdAsync();
        }
        
        public MVCAuthentication.ServiceReference1.CompositeType GetDataUsingDataContract(MVCAuthentication.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MVCAuthentication.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(MVCAuthentication.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ApplicationService.DTOs.BrandDTO[] GetBrands(string filter) {
            return base.Channel.GetBrands(filter);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BrandDTO[]> GetBrandsAsync(string filter) {
            return base.Channel.GetBrandsAsync(filter);
        }
        
        public string PostBrand(ApplicationService.DTOs.BrandDTO brandDto) {
            return base.Channel.PostBrand(brandDto);
        }
        
        public System.Threading.Tasks.Task<string> PostBrandAsync(ApplicationService.DTOs.BrandDTO brandDto) {
            return base.Channel.PostBrandAsync(brandDto);
        }
        
        public string PutBrand(ApplicationService.DTOs.BrandDTO brandDto) {
            return base.Channel.PutBrand(brandDto);
        }
        
        public System.Threading.Tasks.Task<string> PutBrandAsync(ApplicationService.DTOs.BrandDTO brandDto) {
            return base.Channel.PutBrandAsync(brandDto);
        }
        
        public ApplicationService.DTOs.BrandDTO GetBrandByID(int id) {
            return base.Channel.GetBrandByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BrandDTO> GetBrandByIDAsync(int id) {
            return base.Channel.GetBrandByIDAsync(id);
        }
        
        public string DeleteBrand(int id) {
            return base.Channel.DeleteBrand(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBrandAsync(int id) {
            return base.Channel.DeleteBrandAsync(id);
        }
        
        public ApplicationService.DTOs.MotorcycleDTO[] GetMotorcycles(string filter) {
            return base.Channel.GetMotorcycles(filter);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.MotorcycleDTO[]> GetMotorcyclesAsync(string filter) {
            return base.Channel.GetMotorcyclesAsync(filter);
        }
        
        public ApplicationService.DTOs.MotorcycleDTO GetMotorcycleByID(int id) {
            return base.Channel.GetMotorcycleByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.MotorcycleDTO> GetMotorcycleByIDAsync(int id) {
            return base.Channel.GetMotorcycleByIDAsync(id);
        }
        
        public string PostMotorcycle(ApplicationService.DTOs.MotorcycleDTO motorcycleDto) {
            return base.Channel.PostMotorcycle(motorcycleDto);
        }
        
        public System.Threading.Tasks.Task<string> PostMotorcycleAsync(ApplicationService.DTOs.MotorcycleDTO motorcycleDto) {
            return base.Channel.PostMotorcycleAsync(motorcycleDto);
        }
        
        public string PutMotorcycle(ApplicationService.DTOs.MotorcycleDTO motorcycleDto) {
            return base.Channel.PutMotorcycle(motorcycleDto);
        }
        
        public System.Threading.Tasks.Task<string> PutMotorcycleAsync(ApplicationService.DTOs.MotorcycleDTO motorcycleDto) {
            return base.Channel.PutMotorcycleAsync(motorcycleDto);
        }
        
        public string DeleteMotorcycle(int id) {
            return base.Channel.DeleteMotorcycle(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteMotorcycleAsync(int id) {
            return base.Channel.DeleteMotorcycleAsync(id);
        }
        
        public ApplicationService.DTOs.SaleDTO[] GetSales(string filter) {
            return base.Channel.GetSales(filter);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.SaleDTO[]> GetSalesAsync(string filter) {
            return base.Channel.GetSalesAsync(filter);
        }
        
        public ApplicationService.DTOs.SaleDTO GetSaleByID(int id) {
            return base.Channel.GetSaleByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.SaleDTO> GetSaleByIDAsync(int id) {
            return base.Channel.GetSaleByIDAsync(id);
        }
        
        public string PostSale(ApplicationService.DTOs.SaleDTO saleDto) {
            return base.Channel.PostSale(saleDto);
        }
        
        public System.Threading.Tasks.Task<string> PostSaleAsync(ApplicationService.DTOs.SaleDTO saleDto) {
            return base.Channel.PostSaleAsync(saleDto);
        }
        
        public string PutSale(ApplicationService.DTOs.SaleDTO saleDto) {
            return base.Channel.PutSale(saleDto);
        }
        
        public System.Threading.Tasks.Task<string> PutSaleAsync(ApplicationService.DTOs.SaleDTO saleDto) {
            return base.Channel.PutSaleAsync(saleDto);
        }
        
        public string DeleteSale(int id) {
            return base.Channel.DeleteSale(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteSaleAsync(int id) {
            return base.Channel.DeleteSaleAsync(id);
        }
    }
}
